module.exports = {
    testcases: [
        {
            input: [['queryDriver Alice']],
            expected: [0],
        },
        {
            input: [['assign Alice North', 'queryDriver Alice']],
            expected: [1],
        },
        {
            input: [['assign Bob East', 'assign Bob East', 'queryLocation East']],
            expected: [2],
        },
        {
            input: [['assign Charlie South', 'assign Don South', 'assign Don South', 'query Don South']],
            expected: [2],
        },
        {
            input: [
                [
                    'assign Charlie South',
                    'assign Don North',
                    'assign Don North',
                    'assign Alice North',
                    'assign Bob South',
                    'query Don South',
                    'queryLocation North',
                    'queryLocation South',
                    'query Bob South',
                ],
            ],
            expected: [0, 3, 2, 1],
        },
        {
            input: [
                [
                    'assign Alice North',
                    'assign Bob South',
                    'assign Alice South',
                    'queryDriver Alice',
                    'queryLocation South',
                    'query Alice South',
                    'queryDriver Charlie',
                    'assign Charlie South',
                    'queryDriver Charlie',
                ],
            ],
            expected: [2, 2, 1, 0, 1],
        },
        {
            input: [
                [
                    'assign Ethan East',
                    'assign Ethan West',
                    'assign Ethan West',
                    'assign Don South',
                    'assign Bob West',
                    'assign Charlie East',
                    'assign Frank North',
                    'assign Bob West',
                    'assign Ethan West',
                    'assign Bob East',
                    'assign Bob West',
                    'assign Charlie West',
                    'assign Bob West',
                    'assign Don South',
                    'assign Frank West',
                    'assign Charlie West',
                    'assign Frank West',
                    'assign Ethan South',
                    'assign Charlie South',
                    'assign Don East',
                    'assign Charlie South',
                    'queryLocation North',
                    'queryLocation West',
                    'queryDriver Don',
                    'queryLocation South',
                    'queryLocation East',
                    'queryLocation North',
                    'queryDriver Frank',
                    'query Bob East',
                    'query Ethan East',
                    'queryDriver Don',
                    'queryDriver Charlie',
                    'queryDriver Charlie',
                    'query Charlie South',
                    'assign Ethan North',
                    'queryLocation East',
                    'queryLocation East',
                    'assign Charlie West',
                    'queryLocation North',
                    'queryDriver Don',
                    'assign Bob South',
                    'query Ethan West',
                    'query Frank South',
                    'assign Don North',
                    'queryDriver Bob',
                    'queryDriver Bob',
                    'queryLocation East',
                    'query Charlie South',
                    'queryDriver Alice',
                    'queryDriver Bob',
                    'queryDriver Charlie',
                    'queryDriver Don',
                    'queryDriver Alice',
                    'query Bob North',
                    'query Bob West',
                    'queryLocation East',
                    'queryLocation South',
                    'query Bob West',
                    'queryLocation West',
                    'assign Charlie West',
                    'queryDriver Frank',
                    'assign Don North',
                    'query Bob East',
                    'query Bob South',
                    'query Charlie West',
                    'queryLocation West',
                    'query Frank North',
                    'query Don South',
                    'queryDriver Bob',
                    'queryLocation West',
                    'assign Alice West',
                    'queryDriver Don',
                    'queryLocation South',
                    'queryDriver Don',
                    'queryDriver Don',
                    'queryLocation East',
                    'assign Don West',
                    'query Ethan West',
                    'query Charlie East',
                    'queryDriver Alice',
                    'queryDriver Frank',
                    'assign Bob North',
                    'assign Frank East',
                    'query Bob South',
                    'queryLocation East',
                    'queryLocation South',
                    'queryLocation West',
                    'queryDriver Frank',
                    'queryLocation East',
                    'assign Bob South',
                    'queryLocation North',
                    'query Alice North',
                    'query Frank West',
                    'assign Ethan East',
                    'assign Frank West',
                    'queryLocation West',
                    'assign Bob North',
                    'queryDriver Frank',
                    'queryDriver Bob',
                    'query Don South',
                    'queryLocation North',
                    'queryLocation North',
                    'assign Ethan West',
                    'queryLocation North',
                    'queryDriver Bob',
                    'query Ethan East',
                    'assign Frank North',
                    'queryLocation East',
                    'query Don North',
                    'queryLocation West',
                    'assign Frank West',
                    'query Alice North',
                    'assign Frank East',
                    'queryLocation North',
                    'queryDriver Don',
                    'queryDriver Frank',
                    'query Ethan East',
                    'queryDriver Ethan',
                    'queryLocation North',
                    'queryLocation North',
                ],
            ],
            expected: [
                1, 11, 3, 5, 4, 1, 3, 1, 1, 3, 5, 5, 2, 4, 4, 2, 3, 3, 0, 6, 6, 4, 2, 0, 6, 6, 4, 0, 0, 4, 4, 6, 4, 12,
                3, 1, 1, 4, 13, 1, 2, 6, 13, 5, 6, 5, 5, 4, 3, 1, 1, 3, 1, 5, 6, 15, 4, 5, 5, 0, 2, 16, 5, 9, 2, 6, 6,
                6, 9, 2, 6, 2, 17, 0, 7, 6, 8, 2, 8, 7, 7,
            ],
        },
    ],
    options: {
        type: 'JSON',
    },
};
