module.exports = {
    testcases: [
        {
            inputs: [
                ['north', 'south', 'south'],
                ['north', 'south', 'east'],
                ['north', 'south', 'west'],
                ['north', 'east', 'south'],
                ['north', 'east', 'east'],
                ['north', 'east', 'west'],
                ['north', 'west', 'south'],
                ['north', 'west', 'east'],
                ['north', 'west', 'west'],
                ['south', 'north', 'north'],
                ['south', 'north', 'east'],
                ['south', 'north', 'west'],
                ['south', 'east', 'north'],
                ['south', 'east', 'east'],
                ['south', 'east', 'west'],
                ['south', 'west', 'north'],
                ['south', 'west', 'east'],
                ['south', 'west', 'west'],
                ['east', 'north', 'north'],
                ['east', 'north', 'south'],
                ['east', 'north', 'west'],
                ['east', 'south', 'north'],
                ['east', 'south', 'south'],
                ['east', 'south', 'west'],
                ['east', 'west', 'north'],
                ['east', 'west', 'south'],
                ['east', 'west', 'west'],
                ['west', 'north', 'north'],
                ['west', 'north', 'south'],
                ['west', 'north', 'east'],
                ['west', 'south', 'north'],
                ['west', 'south', 'south'],
                ['west', 'south', 'east'],
                ['west', 'east', 'north'],
                ['west', 'east', 'south'],
                ['west', 'east', 'east'],
            ],
            expected: [
                'Proceed',
                'Proceed',
                'Stop',
                'Proceed',
                'Proceed',
                'Stop',
                'Stop',
                'Stop',
                'Stop',
                'Proceed',
                'Stop',
                'Proceed',
                'Stop',
                'Stop',
                'Stop',
                'Proceed',
                'Stop',
                'Proceed',
                'Stop',
                'Stop',
                'Stop',
                'Stop',
                'Proceed',
                'Proceed',
                'Stop',
                'Proceed',
                'Proceed',
                'Proceed',
                'Stop',
                'Proceed',
                'Stop',
                'Stop',
                'Stop',
                'Proceed',
                'Stop',
                'Proceed',
            ],
        },
    ],
};
